# config/meta.yml
default_title: "Sportifly"
meta_description: "Partager, autre chose"
meta_image: "header2.jpg" # Une image dans votre dossier app/assets/images/
twitter_account: "@sportifly_" #indispensable pour les Twitter Cards
