# config/meta.yml
meta_product_name: "Meetemps"
meta_description: "Partager, autre chose"
meta_image: "creative/header3.jpg" # Une image dans votre dossier app/assets/images/
twitter_account: "@meetemps" #indispensable pour les Twitter Cards
